language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --features "dev"
  - cargo build --verbose --no-default-features --features "libm"
  - cargo build --verbose
  - cargo test --verbose --no-default-features --features "libm"
  - cargo test --verbose
